version: '3'

# for debugging only, extend/override this file for production usage (if you are using docker-compose in production at all)
# also see the Dockerfile
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    expose:
      - "2181"
      - "2888"
      - "32181"
      - "3888"
    extra_hosts:
      - "moby:127.0.0.1"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    expose:
      - "9092"
      - "29092"
    extra_hosts:
      - "moby:127.0.0.1"
    # command: "bash -c 'echo Kafka is waiting 20 seconds for zookerkeepr to be ready, before creating a topic... && \
    #      sleep 20 && \
    #      echo Creating topic && \
    #      kafka-topics --create --topic events --partitions 1 --replication-factor 1 --if-not-exists --zookeeper zookeeper:32181 && \
    #      echo Checking topic creation && \
    #      echo docker-compose exec kafka kafka-topics --describe --topic events --zookeeper zookeeper:32181 '"      

  cloudera:
    image: midsw205/cdh-minimal:latest
    expose:
      - "8020" # nn
      - "50070" # nn http
      - "8888" # hue
    #ports:
    #- "8888:8888"
    extra_hosts:
      - "moby:127.0.0.1"

  spark:
    image: midsw205/spark-python:0.0.5
    stdin_open: true
    tty: true
    expose:
      - "8888"
    ports:
      - "8888:8888"
    volumes:
      - "~/w205/project3:/app"
    command: bash
    depends_on:
      - cloudera
    environment:
      HADOOP_NAMENODE: cloudera
    extra_hosts:
      - "moby:127.0.0.1"

  mids:
    image: midsw205/base:latest
    build: flask-app/
    ports:
      - "5000:5000" # app 
      - "5001:5001" # debug
      - "3000:3000" # remote debugger
    volumes:
      - ./flask-app:/usr/src/app/
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=app.py
      - FLASK_ENV=development
    command: flask run --host 0.0.0.0 
    extra_hosts:
      - "moby:127.0.0.1"

